dist: bionic
sudo: false
matrix:
  include:
  - language: node_js
    node_js:
    - '10'
    install: true
    sudo: required
    services:
    - docker
    script:
      - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash buildprocess/ci-deploy.sh; fi'
    after_failure:
      - http POST "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/statuses/${TRAVIS_COMMIT}" "Authorization:token ${GITHUB_TOKEN}" state=failure context=deployment "target_url=${TRAVIS_JOB_WEB_URL}"
    env:
    - NODE_OPTIONS=--max_old_space_size=4096
    - secure: bV2Mb/mIGY5eGXj9CAnimUorNJ7xHqyXK+wn4zWLIRJq1/dkV50r+49LmJH9zVDPe9vByYJJvRf2oqPEqbgcFl4zux+H+lGgVSRcHhngRpi+wLAvYBeYSn4hq/c/uCQme7jViBZQgTXF0l5Aw461AO5NyftyN7Ns+I4JJ9neync=
    - secure: XuhhOSoc2lRvrcen2Fpv/cy7GxhXH0WmnkCb6e/bmUjTrqSaJNdCoOzq4uEX3Ry0A82cf3VmBN0Ukq4w+CQD6rFaONk97XKvjP1ELsU86md1KuwnZkzdeZA1E6R/1tUkUvQ87WPnAsg8GYh/RxUUJtmjJv2b5roXEuIscyUCVKM=
    - secure: YHBdXJwydremwVc01QBBwFABxIjgv3IE3wcD7BJKHnLLSBna+j+96B9U6qTvNE7voO21+w5vCb2L0L0ctJqK0P4OBOHx3MVgnxKEKzXX4tYqSiA1CpQ7oYtzFHZ1SrCNKq/Y6DReCUP9MHfo9eygsXYHP8CDBVzgMF50CmJc1dY=
    - secure: YSuJzfGTwXSUq0liAMsC5yqg6yukPHnFKKCC3/sOeh8UqdCPrS2S37lyg8niA3dNEY+VAa+iYdjRQDUDsAQhQ+FBe7Um4Cz8NEB4t8KjiYiHu+SaRDyubGl4lQRr8n7mrlQ6Xp/lqJZbHdKvYeJMKtSev49/bImq4lHm23vRwro=
